-- CLS Leave & Claims production schema.
-- The authoritative rollout SQL is maintained in:
--
--   supabase/v1-rollout.sql
--
-- Apply that file in the Supabase SQL editor before deploying the Vercel build.
